name: release

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write

jobs:
  release:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/release.yml@v0
